version: "3.8"

services:
  carla:
    build:
      context: ./carla
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SDL_VIDEODRIVER=x11
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 2000:2000
      - 2001:2001
      - 2002:2002
    entrypoint: "./CarlaUE4.sh -opengl -quality-level=Low -ResX=480 -ResY=640 -benchmark"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2000"]
      interval: 20s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
        - CARLA_SERVER_IP=carla
        - CARLA_SERVER_PORT=2000
    volumes:
      - ./client/src:/usr/client/src
    depends_on:
      carla:
        condition: service_healthy
